CREATE TABLE IF NOT EXISTS PRICE_HISTORY
(
EXTRACTION_DATE DATE PRIMARY KEY DEFAULT (datetime('now', 'localtime')),
BUY_PRICE FLOAT,
BUY_PRICE_CURRENCY VARCHAR(6),
SPOT_PRICE FLOAT,
SPOT_PRICE_CURRENCY VARCHAR(6),
SELL_PRICE FLOAT,
SELL_PRICE_CURRENCY VARCHAR(6)
);

CREATE TABLE IF NOT EXISTS INDICATORS
(
CALCULATION_DATE DATE PRIMARY KEY DEFAULT (datetime('now', 'localtime')),
SPOT_PRICE FLOAT,
BUY_PRICE FLOAT,
SELL_PRICE FLOAT,
MA24 FLOAT,
UPPER_BOLLINGER FLOAT,
LOWER_BOLLINGER FLOAT,
AVG_GAIN FLOAT,
AVG_LOSS FLOAT,
RSI FLOAT
);

CREATE TABLE IF NOT EXISTS USERS
(
ID VARCHAR(50) PRIMARY KEY,
NAME VARCHAR(40),
EMAIL VARCHAR(40),
USERNAME VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS BUY_HISTORY
(
BUY_ID VARCHAR(50) PRIMARY KEY,
BUY_DATE DATE DEFAULT (datetime('now', 'localtime')),
BUY_AMOUNT FLOAT,
BUY_PRICE FLOAT,
BUY_PRICE_CURRENCY VARCHAR(20),
BUY_FEE FLOAT,
BUY_TOTAL_PRICE FLOAT
);

CREATE TABLE IF NOT EXISTS SELL_HISTORY
(
SELL_ID VARCHAR(50) PRIMARY KEY,
SELL_DATE DATE DEFAULT (datetime('now', 'localtime')),
SELL_AMOUNT FLOAT,
SELL_PRICE FLOAT,
SELL_PRICE_CURRENCY VARCHAR(20),
TOTAL_SALE_PRICE FLOAT,
GAIN_LOSS_PERCENT FLOAT -- (SELL_PRICE /BUY_PRICE)-1
);